stages:
  - deploy

cache:
  paths:
    - ./node_modules
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull

include:
  - project: 'BAPSoftware/outsource/bapsw.s0142.goemon/goemon-devops'
    ref: main
    file: 'gitlab-templates/goemon-web-user/dev.gitlab-ci.yml'
