export const COIN_SYMBOL = {
	ETH: 'ETH',
	BNB: 'BNB',
	SPC: 'SPC',
	ERC20: 'ERC20',
	HTC: 'HTC',
	PRZ: 'PRZ',
	USDT: 'USDT',
	BUSD: 'BUSD',
	CCT: 'CCT',
	USD: 'USD',
};

export const TYPE_TRANSACTION = {
  CLAIM: 'CLAIM',
  APPROVE: 'APPROVE',
  APPROVED: 'APPROVED',
  CONFIRM: 'CONFIRM',
  CONFIRMED: 'CONFIRMED',
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  SAVING: 'SAVING',
  SAVED: 'SAVED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED',
}